name: Taskbar Build

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    env:
      ASPNETCORE_ENVIRONMENT: Production
    steps:
    - name: Git - Checkout
      uses: actions/checkout@v2
    - name: .NET - Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
